services:
  - type: web
    name: camsociety-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /health-check
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: APP_KEY
        generateValue: true
      - key: ASSET_URL
        sync: false # Set this manually after Vercel deployment
