services:
  - type: web
    name: camsociety
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: APP_KEY
        value: base64:natLseq+3S9jnCN+XO17BHzgM7WhcY/EPZ2x3epAIVE=
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: ASSET_URL
        sync: false # Set this manually after Vercel deployment
      - key: APP_URL
        value: https://camsociety-backend.onrender.com
